<a href="https://colab.research.google.com/github/priyarajmohan/ML_projects/blob/main/animal_check_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
animal = pd.read_csv('/content/zoo_data-1.csv')

In [ ]:
animal

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  
0          1  
1          1  
2          0  
3          1  
4          1  
..       ...  
96         1  
97         0  
98         1  
99         0  
100        0  

[101 rows x 17 columns]

In [ ]:
animal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   animal_name  101 non-null    object
 1   hair         101 non-null    int64 
 2   feathers     101 non-null    int64 
 3   eggs         101 non-null    int64 
 4   milk         101 non-null    int64 
 5   airborne     101 non-null    int64 
 6   aquatic      101 non-null    int64 
 7   predator     101 non-null    int64 
 8   toothed      101 non-null    int64 
 9   backbone     101 non-null    int64 
 10  breathes     101 non-null    int64 
 11  venomous     101 non-null    int64 
 12  fins         101 non-null    int64 
 13  legs         101 non-null    int64 
 14  tail         101 non-null    int64 
 15  domestic     101 non-null    int64 
 16  catsize      101 non-null    int64 
dtypes: int64(16), object(1)
memory usage: 13.5+ KB


In [ ]:
animal.head()

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0        1         1         1         0     0     4     0         0        1  
1        1         1         1         0     0     4     1         0        1  
2        1         1         0         0     1     0     1         0        0  
3        1         1         1         0     0     4     0         0        1  
4        1         1         1         0     0     4     1         0        1

In [ ]:
animal.isnull().sum()

animal_name    0
hair           0
feathers       0
eggs           0
milk           0
airborne       0
aquatic        0
predator       0
toothed        0
backbone       0
breathes       0
venomous       0
fins           0
legs           0
tail           0
domestic       0
catsize        0
dtype: int64

In [ ]:
animal.duplicated().sum()

np.int64(0)

In [ ]:
X = animal.drop('eggs',axis=1)
y = animal['eggs']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_X = {}
for i in X.select_dtypes(include='object'):
  le = LabelEncoder()
  le_X[i]=le

In [ ]:
le_X

{'animal_name': LabelEncoder()}

In [ ]:
X

animal_name  hair  feathers  milk  airborne  aquatic  predator  toothed  \
0       0.000000   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
1       0.010101   1.0       0.0   1.0       0.0      0.0       0.0      1.0   
2       0.020202   0.0       0.0   0.0       0.0      1.0       1.0      1.0   
3       0.030303   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
4       0.040404   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
..           ...   ...       ...   ...       ...      ...       ...      ...   
96      0.959596   1.0       0.0   1.0       0.0      0.0       0.0      1.0   
97      0.969697   1.0       0.0   0.0       1.0      0.0       0.0      0.0   
98      0.979798   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
99      0.989899   0.0       0.0   0.0       0.0      0.0       0.0      0.0   
100     1.000000   0.0       1.0   0.0       1.0      0.0       0.0      0.0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0         1.0       1.0       0.0   0.0  0.50   0.0       0.0      1.0  
1         1.0       1.0       0.0   0.0  0.50   1.0       0.0      1.0  
2         1.0       0.0       0.0   1.0  0.00   1.0       0.0      0.0  
3         1.0       1.0       0.0   0.0  0.50   0.0       0.0      1.0  
4         1.0       1.0       0.0   0.0  0.50   1.0       0.0      1.0  
..        ...       ...       ...   ...   ...   ...       ...      ...  
96        1.0       1.0       0.0   0.0  0.25   1.0       0.0      1.0  
97        0.0       1.0       1.0   0.0  0.75   0.0       0.0      0.0  
98        1.0       1.0       0.0   0.0  0.50   1.0       0.0      1.0  
99        0.0       1.0       0.0   0.0  0.00   0.0       0.0      0.0  
100       1.0       1.0       0.0   0.0  0.25   1.0       0.0      0.0  

[101 rows x 16 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()

# Apply LabelEncoder to the 'animal_name' column
#X['animal_name'] = le_X['animal_name'].fit_transform(X['animal_name'])

# Scale the numerical columns
X[X.columns]=mm.fit_transform(X[X.columns])

In [ ]:
X

animal_name  hair  feathers  milk  airborne  aquatic  predator  toothed  \
0       0.000000   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
1       0.010101   1.0       0.0   1.0       0.0      0.0       0.0      1.0   
2       0.020202   0.0       0.0   0.0       0.0      1.0       1.0      1.0   
3       0.030303   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
4       0.040404   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
..           ...   ...       ...   ...       ...      ...       ...      ...   
96      0.959596   1.0       0.0   1.0       0.0      0.0       0.0      1.0   
97      0.969697   1.0       0.0   0.0       1.0      0.0       0.0      0.0   
98      0.979798   1.0       0.0   1.0       0.0      0.0       1.0      1.0   
99      0.989899   0.0       0.0   0.0       0.0      0.0       0.0      0.0   
100     1.000000   0.0       1.0   0.0       1.0      0.0       0.0      0.0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0         1.0       1.0       0.0   0.0  0.50   0.0       0.0      1.0  
1         1.0       1.0       0.0   0.0  0.50   1.0       0.0      1.0  
2         1.0       0.0       0.0   1.0  0.00   1.0       0.0      0.0  
3         1.0       1.0       0.0   0.0  0.50   0.0       0.0      1.0  
4         1.0       1.0       0.0   0.0  0.50   1.0       0.0      1.0  
..        ...       ...       ...   ...   ...   ...       ...      ...  
96        1.0       1.0       0.0   0.0  0.25   1.0       0.0      1.0  
97        0.0       1.0       1.0   0.0  0.75   0.0       0.0      0.0  
98        1.0       1.0       0.0   0.0  0.50   1.0       0.0      1.0  
99        0.0       1.0       0.0   0.0  0.00   0.0       0.0      0.0  
100       1.0       1.0       0.0   0.0  0.25   1.0       0.0      0.0  

[101 rows x 16 columns]

In [ ]:
y

0      0
1      0
2      1
3      0
4      0
      ..
96     0
97     1
98     0
99     1
100    1
Name: eggs, Length: 101, dtype: int64

In [ ]:
animal['eggs'].value_counts()

eggs
1    59
0    42
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)
predicted=lr.predict(X_test)

In [ ]:
lr.score(X_test,y_test)*100

100.0

In [ ]:
animal.columns

Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize'],
      dtype='object')

In [ ]:
def model_prediction(animal_name, hair, feathers, milk, airborne,
       aquatic, predator, toothed, backbone, breathes, venomous,
       fins, legs, tail, domestic, catsize):
  df = pd.DataFrame({'animal_name':animal_name, 'hair':hair, 'feathers':feathers,  'milk':milk, 'airborne':airborne,
       'aquatic':aquatic, 'predator':predator, 'toothed':toothed, 'backbone':backbone, 'breathes': breathes, 'venomous':venomous,
       'fins':fins, 'legs':legs, 'tail':tail, 'domestic': domestic, 'catsize':catsize},index=[0])
  for i in df.select_dtypes(include='object'):
    df[i]=le_X[i].fit_transform(df[i])
  df[df.columns]=mm.fit_transform(df[df.columns])
  return lr.predict(df)




In [ ]:

model_prediction('boar',1,0,1,0,0,1,1,1,1,0,0,4,1,0,1)

array([1])

In [ ]:
model_prediction('bass',	0,	0,	0,	0,	1,	1,	1,	1,	0,	0,	1,	0,	1,	0,	0)

array([1])

In [ ]:
model_prediction('hen',	0,	0,		0,	0,	1,	1,	1,	1,	0,	0,	1,	0,	1,0,	0)

array([1])

In [ ]:
model_prediction('fox',	0,	0,		0,	0,	1,	1,	1,	1,	0,	0,	1,	0,	1,	0,	0)

array([1])