<a href="https://colab.research.google.com/github/priyarajmohan/ML_projects/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

In [ ]:
arr[4]

5

In [ ]:
arr[1:4]

[2, 3, 4]

In [ ]:
arr[2:12:2]

[3, 5, 7, 9, 11]

In [ ]:
np.take(arr,[5,6,7])

array([6, 7, 8])

In [ ]:
arr = np.array(arr)
np.put(arr,[10,11],[20,30])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 30, 13, 14, 15])

In [ ]:
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5,])

In [ ]:
np.add(a,b)

array([11, 22, 33, 44, 55])

In [ ]:
np.subtract(a,b)

array([ 9, 18, 27, 36, 45])

In [ ]:
np.multiply(a,b)

array([ 10,  40,  90, 160, 250])

In [ ]:
np.divide(a,b)

array([10., 10., 10., 10., 10.])

In [ ]:
np.power(a,2)

array([ 100,  400,  900, 1600, 2500])

In [ ]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [ ]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [ ]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [ ]:
np.log10(a)

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ])

In [ ]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [ ]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [ ]:
np.tan(a)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061])

In [ ]:
np.dot(a,b)

np.int64(550)

In [ ]:
np.sum(a)

np.int64(150)

In [ ]:
np.mean(a)

np.float64(30.0)

In [ ]:
np.median(a)

np.float64(30.0)

In [ ]:
np.std(a)

np.float64(14.142135623730951)

In [ ]:
np.var(a)

np.float64(200.0)

In [ ]:
np.min(a)

np.int64(10)

In [ ]:
np.max(a)

np.int64(50)